# identity :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

variables:
- group: azure.vars
- group: sonarcloud.vars
- { name: id, value: account }
- { name: directory, value: identity }
- { name: sonar.key, value: accountxyz }
- { name: sonar.name, value: IDENTITY }
- { name: sonar.version, value: '0.0.0' }
- { name: namespace, value: Identity }
- { name: terraform, value: .terraformio }
- { name: webapp, value: aspnet }

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
  paths:
    include:
    - .azure/stages/aspnet.yml
    - .azure/stages/deploy.yml
    - .hashicorp
    - identity

pr:
  branches:
    include:
    - master
  paths:
    include:
    - .azure/stages/aspnet.yml
    - .azure/stages/deploy.yml
    - .hashicorp
    - identity

stages:
- template: ../../.azure/stages/aspnet.yml
  parameters:
    id: $(id)
- template: ../../.azure/stages/deploy.yml
  parameters:
    id: $(id)
